local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  -- C++ Makefile template
  s("cpp", {
    t({
      "CC = g++",
      "CFLAGS = -Wall -g",
      "SUBFIX = cpp",
      "",
      "WORK_DIR  = $(shell pwd)",
      "SRC_DIR = $(WORK_DIR)/src",
      "OBJ_DIR = $(WORK_DIR)/obj",
      "INC_PATH = $(WORK_DIR)/inc",
      "DST_DIR = $(WORK_DIR)/bin",
      "TESTS_DIR = $(WORK_DIR)/tests",
      "",
      "SRC = $(wildcard $(SRC_DIR)/*.$(SUBFIX))",
      "OBJS = $(patsubst $(SRC_DIR)/%.$(SUBFIX), $(OBJ_DIR)/%.o, $(SRC))",
      "TARGET = $(DST_DIR)/"
    }),
    i(1, "program"),
    t({
      "",
      "",
      "TESTS = $(wildcard $(TESTS_DIR)/*.sh)",
      "",
      "",
      "$(shell [ -d $(SRC_DIR) ] || mkdir -p $(SRC_DIR) )",
      "$(shell [ -d $(INC_PATH) ] || mkdir -p $(INC_PATH) )",
      "$(shell [ -d $(OBJ_DIR) ] || mkdir -p $(OBJ_DIR) )",
      "$(shell [ -d $(DST_DIR) ] || mkdir -p $(DST_DIR) )",
      "$(shell [ -d $(TESTS_DIR) ] || mkdir -p $(TESTS_DIR) )",
      "",
      "ALL: $(TARGET)",
      "",
      "$(TARGET): $(OBJS)",
      "\t$(CC) -o $@ $^ $(CFLAGS)",
      "",
      "$(OBJS):$(OBJ_DIR)/%.o:$(SRC_DIR)/%.$(SUBFIX)",
      "\t$(CC) -c $< -o $@ -I $(INC_PATH) $(CFLAGS)",
      "",
      "test: $(TARGET)",
      "\t$(MAKE) $(TESTS)",
      "\t@printf '\\e[32mPassed all tests\\e[0m\\n'",
      "",
      "$(TESTS):",
      "\t@echo",
      "\t@echo '============'",
      "\t@printf \"\\e[35mTesting $(notdir $@) \\e[0m\\n\"",
      "\t@$@",
      "\t@printf '\\e[32mOK\\e[0m\\n'",
      "\t@echo '============'",
      "\t@echo",
      "",
      "",
      ".PHONY: clean ALL test $(TESTS)",
      "clean:",
      "\t-rm -rf $(DST_DIR) $(OBJ_DIR)"
    }),
    i(0),
  }),

  -- C Makefile template
  s("c", {
    t({
      "CC = gcc",
      "CFLAGS = -Wall -g",
      "SUBFIX = c",
      "",
      "WORK_DIR  = $(shell pwd)",
      "SRC_DIR = $(WORK_DIR)/src",
      "OBJ_DIR = $(WORK_DIR)/obj",
      "INC_PATH = $(WORK_DIR)/inc",
      "DST_DIR = $(WORK_DIR)/bin",
      "TESTS_DIR = $(WORK_DIR)/tests",
      "",
      "SRC = $(wildcard $(SRC_DIR)/*.$(SUBFIX))",
      "OBJS = $(patsubst $(SRC_DIR)/%.$(SUBFIX), $(OBJ_DIR)/%.o, $(SRC))",
      "TARGET = $(DST_DIR)/"
    }),
    i(1, "program"),
    t({
      "",
      "",
      "TESTS = $(wildcard $(TESTS_DIR)/*.sh)",
      "",
      "",
      "$(shell [ -d $(SRC_DIR) ] || mkdir -p $(SRC_DIR) )",
      "$(shell [ -d $(INC_PATH) ] || mkdir -p $(INC_PATH) )",
      "$(shell [ -d $(OBJ_DIR) ] || mkdir -p $(OBJ_DIR) )",
      "$(shell [ -d $(DST_DIR) ] || mkdir -p $(DST_DIR) )",
      "$(shell [ -d $(TESTS_DIR) ] || mkdir -p $(TESTS_DIR) )",
      "",
      "ALL: $(TARGET)",
      "",
      "$(TARGET): $(OBJS)",
      "\t$(CC) -o $@ $^ $(CFLAGS)",
      "",
      "$(OBJS):$(OBJ_DIR)/%.o:$(SRC_DIR)/%.$(SUBFIX)",
      "\t$(CC) -c $< -o $@ -I $(INC_PATH) $(CFLAGS)",
      "",
      "test: $(TARGET)",
      "\t$(MAKE) $(TESTS)",
      "\t@printf '\\e[32mPassed all tests\\e[0m\\n'",
      "",
      "$(TESTS):",
      "\t@echo",
      "\t@echo '============'",
      "\t@printf \"\\e[35mTesting $(notdir $@) \\e[0m\\n\"",
      "\t@$@",
      "\t@printf '\\e[32mOK\\e[0m\\n'",
      "\t@echo '============'",
      "\t@echo",
      "",
      "",
      ".PHONY: clean ALL test $(TESTS)",
      "clean:",
      "\t-rm -rf $(DST_DIR) $(OBJ_DIR)"
    }),
    i(0),
  }),
} 