# ===
# === basic
# ===
# source ~/.config/zsh/ohmyzsh.zsh
source ~/.config/zsh/plugins.zsh

source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh


source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/completion.zsh


source ~/.config/zsh/mappings.zsh

eval "$(starship init zsh)"
